
FILES=pcb.GTO pcb.GTS pcb.GTL pcb.GP1 pcb.G1 pcb.G2 pcb.GP2 pcb.GBL pcb.GTS pcb.GBO pcb.GM5 pcb.TXT  Pick\ Place\ for\ pcb.txt README

DSPboard.outputs.zip: $(FILES)
	zip  DSPboard.output.zip $(FILES)
