#define SXSIZE 300 
#define SHSIZE 256
#define SYSIZE 256
#define COXSIZE 1024
#define COHSIZE 256
#define COYSIZE 1024
#define OUTSPIKELEN 300
#define OUTCONTLEN 200	


// definitions for DSP memory regions
#define FPGA_SAMPLES 0x0000
#define FPGA_EVENTWR 0x4000
#define FPGA_EVENTRD 0x6000
#define FPGA_OUTDATA 0x2000
#define FPGA_ACQBOARD 0x8000

.EXTERN SH12; 
.EXTERN SH34; 
.EXTERN COH; 
.EXTERN SY1; 
.EXTERN SY2; 
.EXTERN SY3;
.EXTERN COY; 

.EXTERN TIMESTAMP; 
.EXTERN MYID; 

.EXTERN NEWSAMPTMP; 
.EXTERN SPIKELEN;
.EXTERN POSTTRIGLEN; 
.EXTERN NOTRIGGERLEN;
.EXTERN NOTRIGGER;


.EXTERN CURRENTPOS;
.EXTERN SX12; 
.EXTERN SX34; 

.EXTERN SGAIN;
.EXTERN SFID;
.EXTERN SHFID;
.EXTERN STHRESH;
.EXTERN SHLEN; 

.EXTERN CODOWNSAMPLE;
.EXTERN COX;
.EXTERN COGAIN;
.EXTERN COCHAN;
.EXTERN COFID;
.EXTERN COHFID;
.EXTERN COHLEN;
.EXTERN CONTLEN;
.EXTERN CONTCNT;
.EXTERN PENDINGOUTSPIKE;
.EXTERN PENDINGOUTCONT;
.EXTERN CMDID;
.EXTERN CMDIDPENDING;
.EXTERN EVENTIN;
.EXTERN EVENTDONE;
.EXTERN EVENTOUT;

.EXTERN OUTSPIKE;
.EXTERN NEWSAMPLES;
.EXTERN INSTATUS; 
.EXTERN OUTCONT; 
	